@WBLMS.API_HostAddress = https://localhost:7184

GET {{WBLMS.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WBLMS.API_HostAddress}}/api/leaverequest

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  "FirstName" : "FirstName",

}

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  //CreateEmployeeDTO
}

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "password": "string",
  "emailAddress": "string113234411",
  "contactNumber": "string11sdf41111",
  "genderId": 1,
  "roleId": 1,
  "managerId" : 1,
  "createdById" : 1
}

###
public record CreateEmployeeDTO
        (
            [Required(ErrorMessage = "FirstName is required")]
            [MaxLength(50)] string FirstName,
            [Required(ErrorMessage = "LastName is required")]
            [MaxLength(50)] string LastName,
            [Required(ErrorMessage = "Password is required")]
            [MaxLength(25)] string Password,
            [Required(ErrorMessage = "EmailAddress is required")]
            string EmailAddress,
            [Required(ErrorMessage = "ContactNumber is required")]
            string ContactNumber,
            [Required(ErrorMessage = "Gender is required")]
            long GenderId,
            long RoleId,
            long ManagerId,
            long CreatedById
        );

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  //CreateEmployeeDTO
}

###

DELETE {{WBLMS.API_HostAddress}}/api/employee/114

###

GET {{WBLMS.API_HostAddress}}/api/employee/0

###

PUT {{WBLMS.API_HostAddress}}/api/employee/0
Content-Type: application/json

"string"

###

PUT {{WBLMS.API_HostAddress}}/api/employee/9
Content-Type: application/json

{
  "id": 9,
  "firstName": "stringstringstringstring9",
  "lastName": "stringstring6",
  "password": "stringstring3",
  "emailAddress": "strinstringstrin234ggvs@@tring",
  "contactNumber": "strings2tring",
  "genderId": 3,
  "roleId": 3,
  "managerId": 8,
  "updatedById": 3
}
###

GET {{WBLMS.API_HostAddress}}/api/employee?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{WBLMS.API_HostAddress}}/api/employee?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{WBLMS.API_HostAddress}}/api/leaverequest/id?id=0

###

POST {{WBLMS.API_HostAddress}}/api/leaverequest
Content-Type: application/json

{

  "employeeId": 2,
  "managerId": 1,
  "leaveTypeId": 2,
  "reason": "reason",
  "numberOfLeaveDays": 2
  
}

###

GET {{WBLMS.API_HostAddress}}/api/employee?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  //CreateEmployeeDTO
}

###

POST {{WBLMS.API_HostAddress}}/api/employee/paginated?page=1&pageSize=5&sortColumn=genderId&sortOrder=desc
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "password": "",
  "emailAddress": "",
  "contactNumber": "",
  "genderId": 0,
  "roleId": 0,
  "managerId" : 0,
  "createdById" : 0
}

###

POST {{WBLMS.API_HostAddress}}/api/employee/paginated?page=0&pageSize=0&sortColumn=string&sortOrder=string
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "password": "",
  "emailAddress": "",
  "contactNumber": "",
  "genderId": 0,
  "roleId": 1,
  "managerId" : 0,
  "createdById" : 0
}

###

DELETE {{WBLMS.API_HostAddress}}/api/employee/3

###

GET {{WBLMS.API_HostAddress}}/api/employee/1

###

PUT {{WBLMS.API_HostAddress}}/api/employee/40
Content-Type: application/json

{
  "id" : 4,
  "FirstName" : "FirstName",
  "LastName" : "LastName",
  "Password" : "Password",
  "EmailAddress" : "emailaddress",
  "ContactNumber" : "1234567890",
  "GenderId" : 3,
  "RoleId" : 2,
  "ManagerId" : 2,
  "UpdatedById" : 1
}

###
long Id,
            [Required(ErrorMessage = "FirstName is required")]
            [MaxLength(50)] string FirstName,
            [Required(ErrorMessage = "LastName is required")]
            [MaxLength(50)] string LastName,
            [Required(ErrorMessage = "Password is required")]
            [MaxLength(25)] string Password,
            [Required(ErrorMessage = "EmailAddress is required")]
            string EmailAddress,
            [Required(ErrorMessage = "ContactNumber is required")]
            string ContactNumber,
            [Required(ErrorMessage = "Gender is required")]
            long GenderId,
            long RoleId,
            long ManagerId,
            long UpdatedById
            
{
  "statusCode": 200,
  "data": {
    "id": 4,
    "firstName": "string",
    "lastName": "string",
    "password": "36B36E53C8E59EB5832510841FCF22B3C6F72DE74FB0D8DC92DEE955FEA87AFD:41EF25E5E5DD3403F70DF54DD078BB5E:50000:SHA256",
    "emailAddress": "string113234411",
    "contactNumber": "string11sdf41111",
    "genderId": 1,
    "roleId": 1,
    "managerId": 1,
    "createdById": 1,
    "createdDate": null
  }
}