@WBLMS.API_HostAddress = https://localhost:7184

GET {{WBLMS.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WBLMS.API_HostAddress}}/api/leaverequest

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  "FirstName" : "FirstName",

}

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  //CreateEmployeeDTO
}

###

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "password": "string",
  "emailAddress": "string11111123234411",
  "contactNumber": "string111123sdf41111",
  "genderId": 1,
  "roleId": 1,
  "managerId" : 1,
  "createdById" : 1
}

###
public record CreateEmployeeDTO
        (
            [Required(ErrorMessage = "FirstName is required")]
            [MaxLength(50)] string FirstName,
            [Required(ErrorMessage = "LastName is required")]
            [MaxLength(50)] string LastName,
            [Required(ErrorMessage = "Password is required")]
            [MaxLength(25)] string Password,
            [Required(ErrorMessage = "EmailAddress is required")]
            string EmailAddress,
            [Required(ErrorMessage = "ContactNumber is required")]
            string ContactNumber,
            [Required(ErrorMessage = "Gender is required")]
            long GenderId,
            long RoleId,
            long ManagerId,
            long CreatedById
        );

POST {{WBLMS.API_HostAddress}}/api/employee
Content-Type: application/json

{
  //CreateEmployeeDTO
}

###

DELETE {{WBLMS.API_HostAddress}}/api/employee/114

###

GET {{WBLMS.API_HostAddress}}/api/employee/0

###

PUT {{WBLMS.API_HostAddress}}/api/employee/0
Content-Type: application/json

"string"

###

PUT {{WBLMS.API_HostAddress}}/api/employee/9
Content-Type: application/json
{
  "id": 9,
  "firstName": "stringstringstringstring9",
  "lastName": "stringstring6",
  "password": "stringstring3",
  "emailAddress": "strinstringstrin234ggvs@@tring",
  "contactNumber": "strings2tring",
  "genderId": 3,
  "roleId": 3,
  "managerId": 8,
  "updatedById": 3
}
###

GET {{WBLMS.API_HostAddress}}/api/employee?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{WBLMS.API_HostAddress}}/api/employee?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{WBLMS.API_HostAddress}}/api/leaverequest/id?id=0

###

POST {{WBLMS.API_HostAddress}}/api/leaverequest
Content-Type: application/json

{
  {
  "employeeId": 2,
  "managerId": 1,
  "leaveTypeId": 0,
  "reason": "string",
  "numberOfLeaveDays": 5
}
}

###
